### PR TITLE
hide add row in header row

### PR DESCRIPTION
**Pull request by lagartoverde**
To be honest I'm not a fan of having a property on the selection just for this, I was thinking that maybe we could expand the isInTable property to include the cell position of the cursor, I think is something to discuss but for now this works :)

### CODE REVIEW

**Review by nvdk — CHANGES_REQUESTED** [review]
The conclusion of our discussion yesterday was to remove the idea of a title/heading row completely.

**Comment by lagartoverde** [comment]
Sorry I didn't pick up that part, then, I will remove it :)

**Review by abeforgit — CHANGES_REQUESTED** [review]
one of the tests is failing (fairly sure its the test that broke because previous assumptions don't hold anymore)
otherwise seems to work well
I have some thoughts about the formatting but until we settle on a redpencil style I'll refrain from being too annoying about these things :stuck_out_tongue:

**Comment by abeforgit** [comment]
**Warning**: the base branch is master, is that on purpose

**Comment by nvdk** [comment]
> **Warning**: the base branch is master, is that on purpose?

Yes we want to push these fixes to the current QA release so they can be included in the sandbox release next week.

**Comment by nvdk** [comment]
> I'm working on disappearing cursor issues for all table commands
> unsure if you need those before you release? I think that might be broken in the current version as well

yes that one should also go to master if possible (so also based from master :))

**Review by nvdk — APPROVED** [review]
Looks good to me, nitpicking: there is a comment in the test about the header that can go now.

**Review by abeforgit — APPROVED** [review]

**Pull request merged**
