### PR TITLE
added ember intl and translated the table commands

### PR DESCRIPTION
**Pull request by lagartoverde**

### CODE REVIEW

**Review by nvdk — APPROVED** [review]
looks good to me!

**Review by abeforgit — COMMENTED** [review]
For me even if my browser is set to english it still shows the dutch version. Same thing whether I run inside GN or not

**Comment by nvdk** [comment]
> For me even if my browser is set to english it still shows the dutch version. Same thing whether I run inside GN or not

Was that in chrome? In firefox it did seem to work correctly for me, though I did have to refresh after changing my preferred language.

**Comment by lagartoverde** [comment]
How are you setting your language?, for me in chrome I had to use a browser extension because it picked up the system language by default

**Comment by nvdk** [comment]
on chrome it does seems broken when you have multiple languages set:
Screenshot from 2021-04-15 17-13-11

**Review by nvdk — CHANGES_REQUESTED** [review]
does not seem to work when multiple locales are set in chrome

**Review by nvdk — APPROVED** [review]

**Pull request merged**
