### PR TITLE
Ignore empty link tags when pasting

### PR DESCRIPTION
**Pull request by lagartoverde**

### CODE REVIEW

**Review by abeforgit — COMMENTED** [review]
I dont really know how to test this
If I just copy `<a>hello</a>` to my clipboard and paste it, it gets inserted as a link cause it hits the else branch on line 187 of content-editable.js (which inserts the clipboard as text and doesnt clean it)

Another thing is that it should also be retested with the new changes in development (which use the command for inserting)
though afaict the cleaning logic is identical so there shouldnt be any issues

**Comment by lagartoverde** [comment]
In which file is that else branch? I tested it linked with GN as it was where the bug originated, and I think we have a different profile for pasting

**Comment by lagartoverde** [comment]
Sorry I'm sleeping and I didn't see the file,
I think you mean this code
```
if (!isInTable && (this.features.isEnabled('editor-html-paste')||
         this.features.isEnabled('editor-extended-html-paste'))&&
         this.hasClipboardHtmlContent(clipboardData) ) {
      try {
        const inputParser = this.features.isEnabled('editor-extended-html-paste') ?
          new HTMLInputParser({}):
          new HTMLInputParser({safeTags: ['p', 'br', 'ol', 'ul', 'li', 'strong', 'u', 'em', 's', 'table', 'thead', 'tbody', 'th', 'tr', 'td']});

        const htmlPaste = clipboardData.getData('text/html');
        const cleanHTML = inputParser.cleanupHTML(htmlPaste);
        inserHtml(cleanHTML);
      }
      catch(e) {
        // fall back to text pasting
        console.warn(e); //eslint-disable-line no-console
        const text = this.getClipboardContentAsText(clipboardData);
        inserHtml(text);
      }
    }

    else {
      const text = this.getClipboardContentAsText(clipboardData);
      inserHtml(text);
    }
  ```
  Right?

**Comment by abeforgit** [comment]
> Sorry I'm sleeping and I didn't see the file,
> I think you mean this code
> 
> ```
> if (!isInTable && (this.features.isEnabled('editor-html-paste')||
>          this.features.isEnabled('editor-extended-html-paste'))&&
>          this.hasClipboardHtmlContent(clipboardData) ) {
>       try {
>         const inputParser = this.features.isEnabled('editor-extended-html-paste') ?
>           new HTMLInputParser({}):
>           new HTMLInputParser({safeTags: ['p', 'br', 'ol', 'ul', 'li', 'strong', 'u', 'em', 's', 'table', 'thead', 'tbody', 'th', 'tr', 'td']});
> 
>         const htmlPaste = clipboardData.getData('text/html');
>         const cleanHTML = inputParser.cleanupHTML(htmlPaste);
>         inserHtml(cleanHTML);
>       }
>       catch(e) {
>         // fall back to text pasting
>         console.warn(e); //eslint-disable-line no-console
>         const text = this.getClipboardContentAsText(clipboardData);
>         inserHtml(text);
>       }
>     }
> 
>     else {
>       const text = this.getClipboardContentAsText(clipboardData);
>       inserHtml(text);
>     }
> ```
> 
> Right?

yes indeed, I hadnt considered different pasting profiles... ill try it out in GN

**Comment by nvdk** [comment]
> If I just copy `<a>hello</a>` to my clipboard and paste it, it gets inserted as a link cause it hits the else branch on line 187 of content-editable.js (which inserts the clipboard as text and doesnt clean it)

I guess this is a bug in general that we should address, in that we should make the text content html safe. This can be as simple as adding the content to a text node first and then reading out the textnode I think

**Comment by abeforgit** [comment]
so in GN this also doesnt work

steps:
- go to about:blank (in chrome)
- edit the body
- insert `<a>hello</a>`
- select element, copy outerHTML
- paste in editor

still gets pasted as a link
maybe my steps are incorrect? if I literally copy the <a>hello</a> text it just inserts as text
Do we have some kind of example document? cause this is about word documents iirc

**Comment by lagartoverde** [comment]
I have been doing [this](https://drive.google.com/file/d/1G56g7vrExSD6OB6MCdFZwV8c-9q8y3Pw/view?usp=sharing) not sure what's the problem with your method to be honest, but I also tried the sample document from the jira issue and it worked

**Comment by abeforgit** [comment]
Well if the sample document works it should be fine
I can't see many situations where people would end up with `<a>` tags without hrefs anyway

**Pull request merged**
