### PR TITLE
when storing the previous selection, clone the anchor nodes

### PR DESCRIPTION
**Pull request by elpoelma**
On each dom selection change, the ModelSelectionTracker stores the current selection in order to be able to compare it with the next selection on the next selection change. This ensures the selection is cloned in the tracker so comparisons in the next selection change are valid.

### CODE REVIEW

**Comment by benjay10** [comment]
Again, can't speak about the correctnes of the changes, but they do seem to have a positive effect on the citaten-plugin! It now triggers better while typing.

**Review by abeforgit — CHANGES_REQUESTED** [review]
this is effectively the same as removing the isSameAsPrevious check, since it will now always return false. If that's what's needed, its better to simply remove the check and avoid the costly cloning.

I can see now why the comparison causes problems: a dom selection only consists of anchor and focusnodes, and offsets within them. The selection can be identical even though the nodes themselves have moved, whereas in the model we care about paths from root. 
So yeah, please remove the whole check altogether, it's incorrect.

**Comment by abeforgit** [comment]
Note this check was put in place to prevent every write to also cause 2 selection changes
debugging a bit, this was actually not caused by what I thought (dom-write causing immediate selectionchange) but simply due to the way the selectionwriter updated the selection (in two steps!)
I have a fix ready

**Comment by nvdk** [comment]
@elpoelma will you optimize the read after write in this PR or can this be merged?

**Comment by elpoelma** [comment]
> @elpoelma will you optimize the read after write in this PR or can this be merged?

This can be merged, I will optimize it at a later time.

**Pull request merged**
