### PR TITLE
Resolve some Embroider issues

### PR DESCRIPTION
**Pull request by Windvis**
### Overview

This resolves some of the errors and warnings that are shown when building under the Embroider "safe" preset.

##### connected issues and PRs:
#945 
#952

### CODE REVIEW

**Comment by Windvis** [comment]
There is still an issue with `@ember/string` but I'm trying to find out what the correct fix is here.

**Comment by Windvis** [comment]
I went with option 1 for now. Personal preference would be to go for option 4 since those addons aren't really maintained, but that can be done in separate PRs.

**Comment by abeforgit** [comment]
I think 4 should be trivial, `htmlSafe` is builtin since at least 3.28 it seems

**Comment by Windvis** [comment]
It was built-in before that as well, as part of the fake `@ember/string` package, but it was moved to `@ember/template` later. So yea, should be trivial. I just wasn't sure about the `ember-feature-flags` usage in the addon (or the plans for that in the future).

**Comment by abeforgit** [comment]
That's a holdover from a long time ago, and we're not planning on using it for anything at the moment, in fact I would really like to minimize the amount of different scenarios we support

so uh yeah safe to remove

**Comment by abeforgit** [comment]
I don't really understand why the ci is failing on the peerdep, since the version you bumped it to doesnt even have a peerdep on ember anymore afaict

**Comment by Windvis** [comment]
v11 of the resolver doesn't support Ember <4.8 it seems. Not sure what the best fix is.
- stay on v8 (+ ember/string devDev)
- use overrides in the scenarios. v8 on 3.28 and v9 on 4.4 LTS (even though it isn't being run at the moment.

**Comment by abeforgit** [comment]
I mean if its this much of a pain im inclined to just drop 3.28 as well if its ok for loket

**Comment by Windvis** [comment]
I just pushed the overrides. 🤞 

> I mean if its this much of a pain im inclined to just drop 3.28 as well if its ok for loket

Yea, I think it's fine to drop support and cut a major 👍 It's just nicer if that's a separate PR 😄.

**Pull request merged**
