### PR TITLE
Reworked RDFa parsing/serializing and UI/UX

### PR DESCRIPTION
**Pull request by elpoelma**
### Overview
This (draft) PR contains a major overhaul on how we handle RDFa in the editor.
Specifically, it contains the following changes/additions:
- Improved parsing/serialization of RDFa.
- Improved UI/UX to allow for users to edit the underlying RDFa in a document. Users can add/edit/remove properties and relationships between resources and nodes.
- Improvements to UI/UX in how we display block nodes inside an editor document.

##### connected issues and PRs:
- [GN-4506](https://binnenland.atlassian.net/browse/GN-4506?atlOrigin=eyJpIjoiYThkZGYzNTBjZDMxNDRiNjlmNjhlMzA4NDQ2MWRmOGEiLCJwIjoiaiJ9)
- [GN-4507](https://binnenland.atlassian.net/browse/GN-4507?atlOrigin=eyJpIjoiMzM4ODFhYzRhMGZlNGYxYjk5MjM2YjAxNDU1N2QwYWMiLCJwIjoiaiJ9)
- [GN-4508](https://binnenland.atlassian.net/browse/GN-4508?atlOrigin=eyJpIjoiMWE2OGE1YjYyMjM0NGE0YmJjOWE2NTQyODVkMzFkMTMiLCJwIjoiaiJ9)
- [GN-4579](https://binnenland.atlassian.net/browse/GN-4579?atlOrigin=eyJpIjoiMDUyMGY5NGViOGY3NGNjYjk5NjkyZjg2M2E4ODUwZDIiLCJwIjoiaiJ9)

### TODOS
- [x] Finish up the parsing/serialization system
- [x] Finish up rdfa commands
- [x] Introduce new interface for properties/backlinks
- [x] Add support for deleting resource/content nodes
- [x] Improve gap-cursor behaviour
- [x] Finish up insert/wrapping of content/resource nodes
- [x] Convert needed nodespecs to be rdfa-aware
- [x] Check ux of isolating/non-isolating rdfa-aware nodes
- [x] Make variables work with content/resource node system

### CODE REVIEW

**Comment by elpoelma** [comment]
The reason why playwright is failing is due to a visual regression: `li` element now have `div` elements inside of them. These `div` elements have a `margin-top` of 1.2rem (as defined in https://github.com/lblod/ember-rdfa-editor/blob/46821444607a91e47ef16598e49f99f76daf2be2/app/styles/ember-rdfa-editor/_c-content.scss#L122-L130)

**Comment by elpoelma** [comment]
There are still 2 failing tests:
- rdfa | parsing: it should convert rdfa correctly
- rdfa | parsing: it should convert rdfa with property spans correctly
These tests fail due to a (wrong) assumption that the `__rdfaId` is not stripped out when loading html in the editor. I'll check if I can adapt them so they do not rely on the `__rdfaId` attribute.

**Comment by elpoelma** [comment]
We could also adapt the `html-cleaner` to not strip out `__rdfaId` attribute if it finds them.

**Comment by elpoelma** [comment]
It also does not help that these test cases have `div` elements contained in `span` elements.

**Comment by abeforgit** [comment]
I think its better to keep stripping the id and adjust the tests

**Pull request merged**
