### PR TITLE
`Heading` menu dropdown is not fully visible on small editor views

### PR DESCRIPTION
**Pull request by usrtim**

### CODE REVIEW

**Comment by usrtim** [comment]
This PR will fix the problem with hidden overflow , I tested it and everything looks fine but I’m not sure if there will be any other side-effects.

**Review by elpoelma — CHANGES_REQUESTED** [review]
I'm afraid this introduces another issue: on smaller displays the toolbar is not fixed at the top any longer. Additionally, the heading menu should also be fully visible on PC-sized displays but where the editor instance itself does not take up the whole page, so for that case, the @media css selector won't work as expected.

**Comment by abeforgit** [comment]
Ok so
It seems you misunderstood the problem. The issue is that if the div container the editor has a limited height, the headings menu is cut off. Media queries are not relevant here since it has nothing to do with screen size.

**Comment by usrtim** [comment]
> Ok so It seems you misunderstood the problem. The issue is that if the div container the editor has a limited height, the headings menu is cut off. Media queries are not relevant here since it has nothing to do with screen size.

@abeforgit as we agreed, the solution here was to remove overflow: hidden from main container. Please have a look in your spare time.

**Pull request merged**
