### PR TITLE
Ensure `rdfa-parsing` unit tests run correctly

### PR DESCRIPTION
**Pull request by elpoelma**
### Overview
This PR includes the following changes:
- Addition of a `deepArrayContains` extension to qunit-assert
- Modifications to the `rdfa-parsing` unit tests to ensure these run

##### connected issues and PRs:
None

### How to test/reproduce
- Observe that all tests succeed (especially the `rdfa-parsing` tests)

### Challenges/uncertainties
While (if strictly following their interfaces) the objects/subjects of node properties/backlinks should follow the `RDF.Term` interfaces, they currently do not. It is currently not possible to deep compare NamedNodes constructed by `sayDataFactory.namedNode` and objects present in properties/backlinks.
The objects/subjects of properties/backlinks lack the `equals` method. This is due to `JSON.parse` and `JSON.serialize`.

Possible solution to this problem:
- When calling `JSON.parse` when parsing incoming-triples/outgoing-triples, we could configure it to recreate `RDF.Term` objects (literals, namednodes etc.)
- Find another way to pass the incoming-triples/outgoing-triples than using JSON serialization.

### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] UI: feedback for any loading/error states
- [x] Check cancel/go-back flows
- [x] Check database state correct when deleting/updating (especially regarding relationships)
- [x] changelog
- [x] npm lint
- [x] no new deprecations

### CODE REVIEW

**Comment by abeforgit** [comment]
cfr equals: was kinda the reason to remake those interfaces so that we could drop that requirement
could we just make a separate simple equals function?

**Review by abeforgit — APPROVED** [review]

**Comment by elpoelma** [comment]
We can also adapt our `factory` to no longer extend from `DataFactory` and make objects without `equals` function. This way they can be easily parsed/serialized.

**Comment by abeforgit** [comment]
ok that doesnt look too bad, go for it

**Comment by elpoelma** [comment]
> ok that doesnt look too bad, go for it

I'm going to put the JSON parsing/serialization reviving in a different PR, mainly for clarity.

**Pull request merged**
