### PR TITLE
Delete handler

### PR DESCRIPTION
**Pull request by RobbeDP**
A first attempt to implement a new delete handler.
Branched from #146.

### CODE REVIEW

**Comment by lagartoverde** [comment]
https://user-images.githubusercontent.com/17006446/131498167-97264619-b06a-4699-8b59-f6b94a3aa3bd.mov

Sometimes the delete gets stuck, otherwise works great, I tested with the lists template

**Review by lagartoverde — CHANGES_REQUESTED** [review]
Delete gets stuck as indicated above

**Comment by Asergey91** [comment]
> Delete gets stuck as indicated above

I mean you could argue that its intended behaviour.... that being said we really do have vastly different behaviours in lists/tables/text do we have some abstraction for that?

**Comment by lagartoverde** [comment]
> > Delete gets stuck as indicated above
> 
> I mean you could argue that its intended behaviour....

The problem is that sometimes it works sometimes it doesn't with the same blocks, I'm okay with either approach but we want to be consistent :)

**Pull request merged**
