### PR TITLE
Update eslint and various non-ember plugins to latest

### PR DESCRIPTION
**Pull request by abeforgit**
Leaving the ember ones cause they might be tied to ember version, it seems ember-cli-upgrade bumps those

### CODE REVIEW

**Comment by abeforgit** [comment]
seems to break the build _sigh_

**Comment by abeforgit** [comment]
fixed by reverting eslint-prettier
see https://github.com/prettier/eslint-plugin-prettier/issues/434

**Comment by nvdk** [comment]
I think at least eslint etc are also managed by ember-cli, so might not be the best idea to upgrade them separately?

**Comment by nvdk** [comment]
Since I squash merged some PRs I've rebased this one on dev.

**Comment by abeforgit** [comment]
wont squash merging break the lerna-changelogs?

**Comment by abeforgit** [comment]
> I think at least eslint etc are also managed by ember-cli, so might not be the best idea to upgrade them separately?

hmm what does "managed" mean in this case? just that it installs and upgrades it?
if so I dont really see the harm tbh

**Pull request merged**
