### PR TITLE
GN-4224: Backspace into nested lists fix

### PR DESCRIPTION
**Pull request by dkozickis**
Buggy behaviour was Initially introduced here - https://github.com/lblod/ember-rdfa-editor/pull/659, Not sure what was the reasoning apart from the one mentioned in the PR, can you comment please @lagartoverde?

Video with a bit of a hectic commentary on a video here - https://share.cleanshot.com/yjj4q37J

wasn't able upload it to PR as it is too big

See "Content Expressions" here - https://prosemirror.net/docs/guide/

Ticket - https://binnenland.atlassian.net/browse/GN-4240

### CODE REVIEW

**Comment by abeforgit** [comment]
I think it was to disallow tables in lists :thinking:

**Comment by abeforgit** [comment]
with this change you can't get out of the list by pressing enter anymore...

**Comment by lagartoverde** [comment]
I can confirm I can exit the list using the enter, could you specify maybe what are you doing arne?

> I am unable to backspace or delete the Table into the list. I am able to insert it into the list, yes. Can we merge this PR and I will disable the table button for the link nodes? How does that sound? cc @lagartoverde @abeforgit

Respect to this, I think I would be okay with this, there are other ways a user can get a table into a list item like pasting, but I don't think this is a realistic thing to worry about. Let's see also what Arne thinks

**Comment by abeforgit** [comment]
So I could reproduce, but then I reloaded the template and I couldn't anymore :thinking:
so yeah no idea what was going on, maybe a weird state in my localStorage

**Review by abeforgit — APPROVED** [review]

**Pull request merged**
