### PR TITLE
GN-4625: Move to Playwright E2E

### PR DESCRIPTION
**Pull request by dkozickis**
### Overview

Migrate to using Playwright instead of Cypress.

##### connected issues and PRs:

???

### Setup

1. Checkout
2. `npm install`

#### Available commands

* `e2e:open` - opens Playwright UI locally 
* `e2e:open:docker` - opens Playwright UI in Docker and attempts to connect to your XServer 
* `e2e:run` - runs Playwright tests locally, skipping tests tagged with `@vrt`
* `e2e:run:docker` - runs all Playwright tests in Docker
* `e2e:run:vrt` - runs visual regression tests in Docker
* `e2e:run:vrt:update` - updates visual regression tests after running them in Docker
* `e2e:show-report` - shows the report of the last run

#### Visual regression tests (VRT)

To run visual regression tests locally you need to run `npm run e2e:run:vrt`.  
Afterwards if you need to update the snapshots you can run `npm run e2e:run:vrt:update`.

> [!IMPORTANT]
> Playwright is run in Docker to ensure consistent snapshot comparison results, as it guarantees the same environment for each run.

### Challenges/uncertainties

Not sure about behaviour on other host systems, e.g. Linux or Windows.

@abeforgit I am interested to see if you are able to run Dockerized version on your machine with XServer, if you have time to check 🤔 

### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] UI: feedback for any loading/error states
- [x] Check cancel/go-back flows
- [x] Check database state correct when deleting/updating (especially regarding relationships)
- [x] changelog
- [x] npm lint
- [x] no new deprecations

### CODE REVIEW

**Review by abeforgit — COMMENTED** [review]
so the x11 forwarding setup is not working for me and I couldnt find an answer within the hour I gave myself, but thats not blocking for this pr to merge if it works for @piemonkey and @elpoelma 

I do know elena is on wayland, so she might have issues too, but afaik the dockerized setup only matters for VRT right? for functionality tests running playwright natively should be enough?

**Comment by elpoelma** [comment]
I justed tried the x11 forwarding setup. I doesn't seem to work on wayland (as expected, maybe it could be possible with xwayland), but it also does not seem to work on x11.

I'm now looking into running playwright locally, which also has some caveats it seems.

**Comment by elpoelma** [comment]
Update: got it to work on fedora wayland natively (not yet using the x11 forwarding). Was confused on ubuntu being the only 'officially' supported distro, but it also works fine on other distros.

**Comment by elpoelma** [comment]
> @elpoelma good to merge?

Good to merge for me. I can run it locally as expected, and the docker set-up works (albeit without x11 forwarding, but not super crucial IMO). 

One final question: doesn't the fact that playwright uses its own custom browser binaries make the vrt tests also run on the 'same' environment every time. That should be reliable enough no?

**Review by elpoelma — APPROVED** [review]

**Comment by elpoelma** [comment]
> > One final question: doesn't the fact that playwright uses its own custom browser binaries make the vrt tests also run on the 'same' environment every time. That should be reliable enough no?
> 
> The rendering is still going to be different between different OS

true, true.

**Pull request merged**
